elastic_exp:
  of_funcs: [fista, hs, farneback, tvl1, ilk, raft]
  T: null #100
  E: null #500
  nu: null #0.3
  exp_ind: null
  image_id: null
  implot: 3
  vmaxstrain: 0.3
  scale_flow: 0.7
  step_flow: 5
  scale_traction: 4
  step_traction: 1
  T_for_plot: 100
  E_for_plot: 500
  nu_for_plot: 0.45
  threshold_inf: 0
  threshold_sup: 120
  scatter_comparison: True